import { useEffect, useMemo, useRef, useState } from "react";
import { Plus, Trash2, Download, Upload, RotateCcw, Save, AlertTriangle, Pencil } from "lucide-react";
import { menuData as defaultMenuData, CATEGORY_LABELS } from "../data/menu-data";
import type { MenuItem, MenuCategory } from "../types/menu";

const STORAGE_KEY = "smoothie-corner-admin-menu-v1";

const CATEGORIES: MenuCategory[] = ["smoothieBowls", "chiaPuddings", "quickBites", "combos"];

function flatten(data: Record<string, MenuItem[]>): MenuItem[] {
  return Object.values(data).flat();
}

function toGrouped(items: MenuItem[]): Record<string, MenuItem[]> {
  const grouped: Record<string, MenuItem[]> = {
    smoothieBowls: [],
    chiaPuddings: [],
    quickBites: [],
    combos: [],
  };
  items.forEach((item) => grouped[item.category]?.push(item));
  return grouped;
}

const emptyItem = (): MenuItem => ({
  id: `item-${Date.now()}`,
  name: "New Item",
  category: "smoothieBowls",
  price: 0,
  image: null,
  ingredients: [],
  calories: 0,
  protein: "0g",
  benefits: [],
  taste: "",
  available: true,
  featured: false,
});

export default function Admin() {
  const [items, setItems] = useState<MenuItem[]>([]);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [dirty, setDirty] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    document.title = "Admin — Smoothie Corner";
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      try {
        setItems(JSON.parse(saved));
        return;
      } catch {
        /* fall through to defaults */
      }
    }
    setItems(flatten(defaultMenuData));
  }, []);

  const editing = useMemo(() => items.find((i) => i.id === editingId) || null, [items, editingId]);

  function showToast(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  }

  function updateItem(updated: MenuItem) {
    setItems((prev) => prev.map((i) => (i.id === updated.id ? updated : i)));
    setDirty(true);
  }

  function addItem() {
    const item = emptyItem();
    setItems((prev) => [...prev, item]);
    setEditingId(item.id);
    setDirty(true);
  }

  function deleteItem(id: string) {
    if (!confirm("Delete this item? This can't be undone here (export first if unsure).")) return;
    setItems((prev) => prev.filter((i) => i.id !== id));
    if (editingId === id) setEditingId(null);
    setDirty(true);
  }

  function saveToLocalStorage() {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
    setDirty(false);
    showToast("Saved locally in this browser.");
  }

  function resetToDefaults() {
    if (!confirm("Reset all edits back to the original menu data? Local changes will be lost.")) return;
    localStorage.removeItem(STORAGE_KEY);
    setItems(flatten(defaultMenuData));
    setEditingId(null);
    setDirty(false);
    showToast("Reset to the original menu data.");
  }

  function exportData() {
    const grouped = toGrouped(items);
    const fileBody = `// Generated by /admin — paste this into src/data/menu-data.ts\n// replacing the existing \`menuData\` object, then rebuild the site.\nexport const menuData = ${JSON.stringify(grouped, null, 2)};\n`;
    const blob = new Blob([fileBody], { type: "text/typescript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "menu-data.export.ts";
    a.click();
    URL.revokeObjectURL(url);
    showToast("Exported menu-data.export.ts");
  }

  function importData(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      try {
        const text = String(reader.result);
        // Accept either a raw JSON array, or a { category: [...] } grouped object
        const parsed = JSON.parse(text);
        const next: MenuItem[] = Array.isArray(parsed) ? parsed : flatten(parsed);
        setItems(next);
        setDirty(true);
        showToast("Imported menu data. Review, then Save.");
      } catch {
        alert("Couldn't read that file — it needs to be valid JSON exported from this editor.");
      }
    };
    reader.readAsText(file);
    e.target.value = "";
  }

  return (
    <main className="pt-28 pb-24 px-5 md:px-8 min-h-screen bg-cream-soft">
      <div className="mx-auto max-w-6xl">
        <h1 className="font-display text-3xl md:text-4xl font-bold text-ink">Menu Editor</h1>
        <p className="text-ink/60 mt-2 max-w-2xl">
          Add, edit, delete and reorganise menu items. This page runs entirely in your
          browser — nothing is sent anywhere.
        </p>

        <div className="mt-4 flex items-start gap-3 bg-honey/25 border border-honey/50 rounded-2xl p-4 text-sm text-ink/80">
          <AlertTriangle size={18} className="shrink-0 mt-0.5 text-orange-dark" />
          <p>
            <strong>Important:</strong> Smoothie Corner is a static website with no server.
            Changes made here are saved only in <em>this browser</em>. To make them show
            up on the real, deployed site, click <strong>Export Updated Menu</strong>,
            then replace the contents of <code className="bg-white/60 px-1.5 py-0.5 rounded">src/data/menu-data.ts</code> with
            the exported file and rebuild/redeploy.
          </p>
        </div>

        <div className="mt-6 flex flex-wrap gap-3">
          <button onClick={addItem} className="flex items-center gap-2 bg-leaf text-cream font-display font-semibold px-5 py-2.5 rounded-full hover:bg-leaf-dark transition-colors">
            <Plus size={18} /> Add Product
          </button>
          <button onClick={saveToLocalStorage} className="flex items-center gap-2 bg-ink text-cream font-display font-semibold px-5 py-2.5 rounded-full hover:opacity-90 transition-opacity">
            <Save size={18} /> Save {dirty && <span className="w-2 h-2 rounded-full bg-honey" />}
          </button>
          <button onClick={exportData} className="flex items-center gap-2 border-2 border-ink/15 font-display font-semibold px-5 py-2.5 rounded-full hover:border-leaf hover:text-leaf transition-colors">
            <Download size={18} /> Export Updated Menu
          </button>
          <button onClick={() => fileRef.current?.click()} className="flex items-center gap-2 border-2 border-ink/15 font-display font-semibold px-5 py-2.5 rounded-full hover:border-grape hover:text-grape transition-colors">
            <Upload size={18} /> Import Menu Data
          </button>
          <input ref={fileRef} type="file" accept="application/json" onChange={importData} className="hidden" />
          <button onClick={resetToDefaults} className="flex items-center gap-2 text-ink/50 font-display font-medium px-5 py-2.5 rounded-full hover:text-pink transition-colors ml-auto">
            <RotateCcw size={18} /> Reset
          </button>
        </div>

        <div className="mt-10 space-y-10">
          {CATEGORIES.map((cat) => {
            const catItems = items.filter((i) => i.category === cat);
            if (catItems.length === 0) return null;
            return (
              <div key={cat}>
                <h2 className="font-display text-lg font-semibold text-ink/70 mb-3">{CATEGORY_LABELS[cat]}</h2>
                <div className="bg-white/70 rounded-2xl border border-ink/5 divide-y divide-ink/5">
                  {catItems.map((item) => (
                    <div key={item.id} className="flex items-center gap-4 px-5 py-3">
                      <div className="flex-1 min-w-0">
                        <p className="font-display font-medium truncate">
                          {item.name} {!item.available && <span className="text-xs text-pink ml-2">(unavailable)</span>}
                          {item.featured && <span className="text-xs text-honey ml-2">★ featured</span>}
                        </p>
                        <p className="text-xs text-ink/50">₹{item.price} · {item.calories} cal · {item.protein}</p>
                      </div>
                      <button onClick={() => setEditingId(item.id)} className="w-9 h-9 flex items-center justify-center rounded-full bg-ink/5 hover:bg-ink/10" aria-label={`Edit ${item.name}`}>
                        <Pencil size={16} />
                      </button>
                      <button onClick={() => deleteItem(item.id)} className="w-9 h-9 flex items-center justify-center rounded-full bg-pink/10 text-pink hover:bg-pink/20" aria-label={`Delete ${item.name}`}>
                        <Trash2 size={16} />
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {editing && (
        <EditPanel item={editing} onChange={updateItem} onClose={() => setEditingId(null)} />
      )}

      {toast && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 bg-ink text-cream px-5 py-2.5 rounded-full shadow-soft font-display text-sm z-[70]">
          {toast}
        </div>
      )}
    </main>
  );
}

function EditPanel({
  item,
  onChange,
  onClose,
}: {
  item: MenuItem;
  onChange: (item: MenuItem) => void;
  onClose: () => void;
}) {
  const [draft, setDraft] = useState<MenuItem>(item);

  useEffect(() => setDraft(item), [item]);

  function field<K extends keyof MenuItem>(key: K, value: MenuItem[K]) {
    setDraft((d) => ({ ...d, [key]: value }));
  }

  function commit() {
    onChange(draft);
    onClose();
  }

  return (
    <div className="fixed inset-0 z-[70] bg-ink/50 flex items-end md:items-center justify-center" onClick={onClose}>
      <div
        onClick={(e) => e.stopPropagation()}
        className="bg-cream w-full md:max-w-lg md:rounded-[28px] rounded-t-[28px] max-h-[90vh] overflow-y-auto p-6 md:p-8 space-y-4"
      >
        <h2 className="font-display text-xl font-bold">Edit Product</h2>

        <LabeledInput label="Name" value={draft.name} onChange={(v) => field("name", v)} />

        <label className="block">
          <span className="text-sm font-medium text-ink/70">Category</span>
          <select
            value={draft.category}
            onChange={(e) => field("category", e.target.value as MenuCategory)}
            className="mt-1 w-full rounded-xl border border-ink/15 px-3 py-2 bg-white"
          >
            {CATEGORIES.map((c) => (
              <option key={c} value={c}>{CATEGORY_LABELS[c]}</option>
            ))}
          </select>
        </label>

        <div className="grid grid-cols-2 gap-3">
          <LabeledInput label="Price (₹)" type="number" value={String(draft.price)} onChange={(v) => field("price", Number(v) || 0)} />
          <LabeledInput label="Size (optional)" value={draft.size || ""} onChange={(v) => field("size", v)} />
        </div>

        <LabeledInput
          label="Image path (e.g. assets/products/name.webp, no leading slash) — leave blank to show fallback"
          value={draft.image || ""}
          onChange={(v) => field("image", v || null)}
        />

        <LabeledInput label="Description (optional)" value={draft.description || ""} onChange={(v) => field("description", v)} />

        <LabeledInput
          label="Ingredients (comma separated)"
          value={draft.ingredients.join(", ")}
          onChange={(v) => field("ingredients", v.split(",").map((s) => s.trim()).filter(Boolean))}
        />

        <div className="grid grid-cols-2 gap-3">
          <LabeledInput label="Calories" type="number" value={String(draft.calories)} onChange={(v) => field("calories", Number(v) || 0)} />
          <LabeledInput label="Protein (e.g. 18g)" value={draft.protein} onChange={(v) => field("protein", v)} />
        </div>

        <LabeledInput
          label="Nutrition highlights (comma separated)"
          value={draft.benefits.join(", ")}
          onChange={(v) => field("benefits", v.split(",").map((s) => s.trim()).filter(Boolean))}
        />

        <LabeledInput label="Taste profile" value={draft.taste} onChange={(v) => field("taste", v)} />

        <div className="flex gap-6">
          <label className="flex items-center gap-2 text-sm font-medium">
            <input type="checkbox" checked={draft.available} onChange={(e) => field("available", e.target.checked)} />
            Available
          </label>
          <label className="flex items-center gap-2 text-sm font-medium">
            <input type="checkbox" checked={draft.featured} onChange={(e) => field("featured", e.target.checked)} />
            Featured on homepage
          </label>
        </div>

        <div className="flex gap-3 pt-2">
          <button onClick={commit} className="flex-1 bg-leaf text-cream font-display font-semibold py-3 rounded-full hover:bg-leaf-dark transition-colors">
            Apply changes
          </button>
          <button onClick={onClose} className="px-6 font-display font-medium text-ink/60 hover:text-ink">
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
}

function LabeledInput({
  label,
  value,
  onChange,
  type = "text",
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  type?: string;
}) {
  return (
    <label className="block">
      <span className="text-sm font-medium text-ink/70">{label}</span>
      <input
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="mt-1 w-full rounded-xl border border-ink/15 px-3 py-2 bg-white focus:outline-none focus:ring-2 focus:ring-grape/40"
      />
    </label>
  );
}
